//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapToolsWinForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_lon_scale {
            get {
                return ((string)(this["Setting_lon_scale"]));
            }
            set {
                this["Setting_lon_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_lat_scale {
            get {
                return ((string)(this["Setting_lat_scale"]));
            }
            set {
                this["Setting_lat_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_dir_scale {
            get {
                return ((string)(this["Setting_dir_scale"]));
            }
            set {
                this["Setting_dir_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_speed_scale {
            get {
                return ((string)(this["Setting_speed_scale"]));
            }
            set {
                this["Setting_speed_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_alt_scale {
            get {
                return ((string)(this["Setting_alt_scale"]));
            }
            set {
                this["Setting_alt_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_acc_scale {
            get {
                return ((string)(this["Setting_acc_scale"]));
            }
            set {
                this["Setting_acc_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy-MM-dd HH:mm:ss")]
        public string Setting_time_scale {
            get {
                return ((string)(this["Setting_time_scale"]));
            }
            set {
                this["Setting_time_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_time_check {
            get {
                return ((bool)(this["Setting_time_check"]));
            }
            set {
                this["Setting_time_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Setting_type_scale {
            get {
                return ((string)(this["Setting_type_scale"]));
            }
            set {
                this["Setting_type_scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Setting_jump_num {
            get {
                return ((string)(this["Setting_jump_num"]));
            }
            set {
                this["Setting_jump_num"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_separator_idx {
            get {
                return ((int)(this["Setting_separator_idx"]));
            }
            set {
                this["Setting_separator_idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_coord_type_idx {
            get {
                return ((int)(this["Setting_coord_type_idx"]));
            }
            set {
                this["Setting_coord_type_idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_is_filter_0_point {
            get {
                return ((bool)(this["Setting_is_filter_0_point"]));
            }
            set {
                this["Setting_is_filter_0_point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_file_format_idx {
            get {
                return ((int)(this["Setting_file_format_idx"]));
            }
            set {
                this["Setting_file_format_idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_slt_tmap_path {
            get {
                return ((string)(this["Setting_slt_tmap_path"]));
            }
            set {
                this["Setting_slt_tmap_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_is_filter_repeat_point {
            get {
                return ((bool)(this["Setting_is_filter_repeat_point"]));
            }
            set {
                this["Setting_is_filter_repeat_point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public string Setting_min_speed {
            get {
                return ((string)(this["Setting_min_speed"]));
            }
            set {
                this["Setting_min_speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_amap_key {
            get {
                return ((string)(this["Setting_amap_key"]));
            }
            set {
                this["Setting_amap_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_baidu_map_key {
            get {
                return ((string)(this["Setting_baidu_map_key"]));
            }
            set {
                this["Setting_baidu_map_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_tencent_map_key {
            get {
                return ((string)(this["Setting_tencent_map_key"]));
            }
            set {
                this["Setting_tencent_map_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43fba9453caa69b438d977de4e432793")]
        public string Defult_amap_key {
            get {
                return ((string)(this["Defult_amap_key"]));
            }
            set {
                this["Defult_amap_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CQnucm2q5gflDUai9Q9nVWtIhVaZXRIB")]
        public string Defult_baidu_map_key {
            get {
                return ((string)(this["Defult_baidu_map_key"]));
            }
            set {
                this["Defult_baidu_map_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGTBZ-L55RW-UJSRS-RLTUY-E6HB7-WJBC6")]
        public string Defult_tencent_map_key {
            get {
                return ((string)(this["Defult_tencent_map_key"]));
            }
            set {
                this["Defult_tencent_map_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setting_slt_search_engine {
            get {
                return ((int)(this["Setting_slt_search_engine"]));
            }
            set {
                this["Setting_slt_search_engine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_key_word {
            get {
                return ((string)(this["Setting_key_word"]));
            }
            set {
                this["Setting_key_word"] = value;
            }
        }
    }
}
